/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author Depasinre
 */
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;

import java.util.Scanner;
import java.io.File;
import java.io.FileWriter; 
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files; 
import java.nio.file.Path; 
import java.nio.file.Paths; 
import java.util.List;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime; 

public class test_GUI extends javax.swing.JFrame {

    /**
     * Creates new form test_GUI
     */
    public test_GUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_panel = new javax.swing.JPanel();
        username_lable = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        username_button = new javax.swing.JButton();
        display_panel = new javax.swing.JPanel();
        balance_lable = new javax.swing.JLabel();
        dollarsign = new javax.swing.JLabel();
        balance_number = new javax.swing.JLabel();
        goal_panel = new javax.swing.JPanel();
        goal_lable = new javax.swing.JLabel();
        goal_input = new javax.swing.JTextField();
        action_panel = new javax.swing.JPanel();
        deposit_panel = new javax.swing.JPanel();
        deposit_lable = new javax.swing.JLabel();
        deposit_input = new javax.swing.JTextField();
        withdraw_panel = new javax.swing.JPanel();
        withdraw_lable = new javax.swing.JLabel();
        withdraw_input = new javax.swing.JTextField();
        action_button = new javax.swing.JButton();
        logs_panel = new javax.swing.JPanel();
        logs_lable = new javax.swing.JLabel();
        logs_sc_pane = new javax.swing.JScrollPane();
        logs_output = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username_lable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        username_lable.setText("Username:");

        username_input.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        username_input.setForeground(java.awt.Color.gray);
        username_input.setText("Enter Username");
        username_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_inputFocusLost(evt);
            }
        });
        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });

        username_button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        username_button.setText("submit");
        username_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout username_panelLayout = new javax.swing.GroupLayout(username_panel);
        username_panel.setLayout(username_panelLayout);
        username_panelLayout.setHorizontalGroup(
            username_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(username_panelLayout.createSequentialGroup()
                .addComponent(username_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(username_button)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        username_panelLayout.setVerticalGroup(
            username_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, username_panelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(username_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_lable)
                    .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_button))
                .addContainerGap())
        );

        balance_lable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        balance_lable.setText("Current Balance: ");

        dollarsign.setFont(new java.awt.Font("Times New Roman", 0, 23)); // NOI18N
        dollarsign.setText("$");

        balance_number.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        balance_number.setText("0000.00");

        javax.swing.GroupLayout display_panelLayout = new javax.swing.GroupLayout(display_panel);
        display_panel.setLayout(display_panelLayout);
        display_panelLayout.setHorizontalGroup(
            display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display_panelLayout.createSequentialGroup()
                .addComponent(balance_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dollarsign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balance_number)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        display_panelLayout.setVerticalGroup(
            display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(display_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balance_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balance_number)
                    .addComponent(dollarsign, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        goal_lable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        goal_lable.setText("Goal: ");

        goal_input.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        goal_input.setForeground(java.awt.Color.gray);
        goal_input.setText("Setting your goal");
        goal_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                goal_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                goal_inputFocusLost(evt);
            }
        });
        goal_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goal_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout goal_panelLayout = new javax.swing.GroupLayout(goal_panel);
        goal_panel.setLayout(goal_panelLayout);
        goal_panelLayout.setHorizontalGroup(
            goal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goal_panelLayout.createSequentialGroup()
                .addComponent(goal_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goal_input, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        goal_panelLayout.setVerticalGroup(
            goal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goal_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(goal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goal_lable)
                    .addComponent(goal_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        deposit_lable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        deposit_lable.setText("Deposits");

        deposit_input.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        deposit_input.setForeground(java.awt.Color.gray);
        deposit_input.setText("Enter the number");
        deposit_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deposit_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deposit_inputFocusLost(evt);
            }
        });
        deposit_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deposit_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deposit_panelLayout = new javax.swing.GroupLayout(deposit_panel);
        deposit_panel.setLayout(deposit_panelLayout);
        deposit_panelLayout.setHorizontalGroup(
            deposit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deposit_panelLayout.createSequentialGroup()
                .addGroup(deposit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deposit_panelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(deposit_lable))
                    .addGroup(deposit_panelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(deposit_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        deposit_panelLayout.setVerticalGroup(
            deposit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deposit_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deposit_lable)
                .addGap(18, 18, 18)
                .addComponent(deposit_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        withdraw_lable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        withdraw_lable.setText("Withdraw");

        withdraw_input.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        withdraw_input.setForeground(java.awt.Color.gray);
        withdraw_input.setText("Enter the number");
        withdraw_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                withdraw_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                withdraw_inputFocusLost(evt);
            }
        });
        withdraw_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdraw_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout withdraw_panelLayout = new javax.swing.GroupLayout(withdraw_panel);
        withdraw_panel.setLayout(withdraw_panelLayout);
        withdraw_panelLayout.setHorizontalGroup(
            withdraw_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdraw_panelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(withdraw_lable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdraw_panelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(withdraw_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        withdraw_panelLayout.setVerticalGroup(
            withdraw_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdraw_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(withdraw_lable)
                .addGap(18, 18, 18)
                .addComponent(withdraw_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        action_button.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        action_button.setText("confirm");
        action_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout action_panelLayout = new javax.swing.GroupLayout(action_panel);
        action_panel.setLayout(action_panelLayout);
        action_panelLayout.setHorizontalGroup(
            action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_panelLayout.createSequentialGroup()
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(action_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deposit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(withdraw_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(action_panelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(action_button)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        action_panelLayout.setVerticalGroup(
            action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(action_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdraw_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deposit_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(action_button)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        logs_lable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        logs_lable.setText("Logs:");

        logs_output.setColumns(20);
        logs_output.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logs_output.setRows(5);
        logs_sc_pane.setViewportView(logs_output);

        javax.swing.GroupLayout logs_panelLayout = new javax.swing.GroupLayout(logs_panel);
        logs_panel.setLayout(logs_panelLayout);
        logs_panelLayout.setHorizontalGroup(
            logs_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logs_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logs_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logs_sc_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logs_lable))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        logs_panelLayout.setVerticalGroup(
            logs_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logs_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logs_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logs_sc_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(action_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logs_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(display_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(goal_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(username_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(display_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goal_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(action_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logs_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

    private void withdraw_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdraw_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdraw_inputActionPerformed

    private void username_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_buttonActionPerformed
        // TODO add your handling code here:
        logs_output.setText("");
            
    	    String goal_text = goal_input.getText();
            String username_text = username_input.getText();

            int goal_num = 0;
            if (goal_text.equals("Setting your goal")){
              goal_num = 0;
            } else {
              try {
            	  goal_num = Integer.parseInt(goal_text);
              } catch (NumberFormatException e1) {
            	  goal_num = 0;
              }
            }

            if (username_text.equals("Enter Username") || username_text.equals("")){
              System.out.print("bad username");
            } else {
            
	            username_text = username_text.replaceAll(" ", "_");
	        	  readData(username_text, goal_num, logs_output);
            }
           balance_number.setText(""+balance);
           balance_number.revalidate();
    }//GEN-LAST:event_username_buttonActionPerformed

    private void action_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_buttonActionPerformed
        // TODO add your handling code here:\
        int deposit = 0;
        int withdraw = 0;
        
        try {
              deposit = Integer.parseInt(deposit_input.getText());
            } catch (NumberFormatException e1) {
            }
            try {
              withdraw = Integer.parseInt(withdraw_input.getText());
            } catch (NumberFormatException e1) {
            }
            String old_balance = Integer.toString(balance);
            balance = balance + deposit - withdraw;
            balance_number.setText(""+balance);
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDateTime now = LocalDateTime.now();
            String time = dtf.format(now);
            
            logs_output.setText(logs_output.getText()+ time + "\n");
            logs_output.setText(logs_output.getText() + "Deposit amount is " + deposit + "\n");
            logs_output.setText(logs_output.getText() + "Withdraw amount is " + withdraw + "\n");
            logs_output.revalidate();
            try{
              String filename = username_input.getText() + "_data.txt";
              File file = new File(filename);
              Scanner sc = new Scanner(file);
              //instantiating the StringBuffer class
              StringBuffer buffer = new StringBuffer();
              //Reading lines of the file and appending them to StringBuffer
              while (sc.hasNextLine()) {
                buffer.append(sc.nextLine()+System.lineSeparator());
              }
              String fileContents = buffer.toString();
              System.out.println("Contents of the file: "+fileContents);
              sc.close();
              String new_balance = Integer.toString(balance);
              int first_one = fileContents.indexOf(System.lineSeparator());
              int second_one = fileContents.indexOf(System.lineSeparator(),first_one+1);
              int third_one = fileContents.indexOf(System.lineSeparator(),second_one+1);
              fileContents = fileContents.substring(0, second_one+1) + new_balance + fileContents.substring(third_one);
              FileWriter writer = new FileWriter(filename);
              writer.append(fileContents);
              writer.append(deposit + "," + withdraw + "," + time + System.getProperty("line.separator"));
              writer.flush();              
              writer.close();
            }catch(IOException e2){
                
            }
    }//GEN-LAST:event_action_buttonActionPerformed

    private void goal_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goal_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goal_inputActionPerformed

    private void username_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_inputFocusGained
        // TODO add your handling code here:
        if (username_input.getText().equals("Enter Username")) {
                username_input.setText("");
                username_input.setForeground(Color.BLACK);
            }
    }//GEN-LAST:event_username_inputFocusGained

    private void username_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_inputFocusLost
        // TODO add your handling code here:
        if (username_input.getText().isEmpty()) {
                username_input.setForeground(Color.GRAY);
                username_input.setText("Enter Username");
            }
    }//GEN-LAST:event_username_inputFocusLost

    private void goal_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goal_inputFocusGained
        // TODO add your handling code here:
         if (goal_input.getText().equals("Setting your goal")) {
                goal_input.setText("");
                goal_input.setForeground(Color.BLACK);
            }
    }//GEN-LAST:event_goal_inputFocusGained

    private void goal_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_goal_inputFocusLost
        // TODO add your handling code here:
        if (goal_input.getText().isEmpty()) {
                goal_input.setForeground(Color.GRAY);
                goal_input.setText("Enter Goal");
            }
    }//GEN-LAST:event_goal_inputFocusLost

    private void deposit_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deposit_inputFocusGained
        // TODO add your handling code here:
        if (deposit_input.getText().equals("Enter the number")) {
            	  deposit_input.setText("");
            	  deposit_input.setForeground(Color.BLACK);
              }
    }//GEN-LAST:event_deposit_inputFocusGained

    private void deposit_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deposit_inputFocusLost
        // TODO add your handling code here:
        if (deposit_input.getText().isEmpty()) {
            	  deposit_input.setForeground(Color.GRAY);
            	  deposit_input.setText("Enter the number");
              }
    }//GEN-LAST:event_deposit_inputFocusLost

    private void withdraw_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_withdraw_inputFocusGained
        // TODO add your handling code here:
        if (withdraw_input.getText().equals("Enter the number")) {
            	  withdraw_input.setText("");
            	  withdraw_input.setForeground(Color.BLACK);
              }
    }//GEN-LAST:event_withdraw_inputFocusGained

    private void withdraw_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_withdraw_inputFocusLost
        // TODO add your handling code here:
        if (withdraw_input.getText().isEmpty()) {
            	  withdraw_input.setForeground(Color.GRAY);
            	  withdraw_input.setText("Enter the number");
              }
    }//GEN-LAST:event_withdraw_inputFocusLost

    private void deposit_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deposit_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deposit_inputActionPerformed
public static void readData(String username, int goal, JTextArea transactions) {
    try {
      String filename = username + "_data.txt";
      File file = new File(filename);
       if (file.exists()) {
            Scanner sc = new Scanner(file);
            //instantiating the StringBuffer class
            StringBuffer buffer = new StringBuffer();
            //Reading lines of the file and appending them to StringBuffer
            while (sc.hasNextLine()) {
              buffer.append(sc.nextLine()+System.lineSeparator());
            }
            String fileContents = buffer.toString();
            System.out.println("Contents of the file: "+fileContents);
            sc.close();
            String new_balance = Integer.toString(balance);
            int first_one = fileContents.indexOf(System.lineSeparator());
            int second_one = fileContents.indexOf(System.lineSeparator(),first_one+1);
            fileContents = fileContents.substring(0,first_one+1) + Integer.toString(goal) + fileContents.substring(second_one);
            FileWriter writer = new FileWriter(filename);
            writer.append(fileContents);
            writer.flush();              
            writer.close();
      } else {
        file.createNewFile();
        FileWriter writer = new FileWriter(filename);
        writer.write(username + System.getProperty("line.separator"));
        writer.write(goal + System.getProperty("line.separator"));
        writer.write("0" + System.getProperty("line.separator"));
        writer.close();
      }
      
      Statement(filename, transactions);

    } catch(Exception e) {
      e.printStackTrace();
    }
  }
public static void Statement(String filename, JTextArea transactions) {
   try {
     File file = new File(filename);
     Scanner sc = new Scanner(file);
     for (int i = 0; i < 3; i++) { // goes to 4th line
    	 
    	 if (i==2 && sc.hasNextLine()) {
    		  String input = sc.nextLine();
    	    balance = Integer.parseInt(input);
    	 } else if (i==2 && !sc.hasNextLine()) {
          balance = 0;
        } else if (sc.hasNextLine()) {
     	   String input = sc.nextLine();
     	 }
     }
     while (sc.hasNextLine()) {
       String line = sc.nextLine();
       String parsed[] = line.split(","); // 0=deposit, 1=withdraw,
        transactions.setText(transactions.getText()+parsed[2]+"\n");
       transactions.setText(transactions.getText() + "Deposit amount is " + parsed[0] + "\n");
       transactions.setText(transactions.getText() + "Withdraw amount is " + parsed[1] + "\n");
       transactions.revalidate();
     }
   }
   catch(Exception e) {
     e.printStackTrace();
   }
  }

public void windowClosing(WindowEvent e) {
    System.exit(0);
  }

    /**
     * @param args the command line arguments
     */
    public static int balance = 0;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton action_button;
    private javax.swing.JPanel action_panel;
    private javax.swing.JLabel balance_lable;
    private javax.swing.JLabel balance_number;
    private javax.swing.JTextField deposit_input;
    private javax.swing.JLabel deposit_lable;
    private javax.swing.JPanel deposit_panel;
    private javax.swing.JPanel display_panel;
    private javax.swing.JLabel dollarsign;
    private javax.swing.JTextField goal_input;
    private javax.swing.JLabel goal_lable;
    private javax.swing.JPanel goal_panel;
    private javax.swing.JLabel logs_lable;
    private javax.swing.JTextArea logs_output;
    private javax.swing.JPanel logs_panel;
    private javax.swing.JScrollPane logs_sc_pane;
    private javax.swing.JButton username_button;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel username_lable;
    private javax.swing.JPanel username_panel;
    private javax.swing.JTextField withdraw_input;
    private javax.swing.JLabel withdraw_lable;
    private javax.swing.JPanel withdraw_panel;
    // End of variables declaration//GEN-END:variables
}
